### ISSUE TITLE
On Screen keyboard

### ISSUE THREAD

**Issue by deb75** [pschmitt/awesome-config#1]
Hello,

I would like to run your on screen keyboard (osk.lua), but I have run into several bugs I am not skilled enough to solve.

Would you have a look to your code and try it against awesome v4.2 (lua 5.3.3 - debian 10) ?

Regards

**Comment by pschmitt** [comment]
I'm sorry, but I'm not running Awesome anymore. This repo is probably way out of date. Sorry.
